### ISSUE TITLE
👀 Tracking: Onboarding

### ISSUE THREAD

**Issue by mrtopsyt** [uclaacm/pen-pals#60]
### Overview:

Onboard new members for Fall 2023!

### Checklist:

- [ ] Clone Repo - `git clone git@github.com:uclaacm/pen-pals.git`
- [ ] Install Node - should be able to run `node --version`
- [ ] Run `npm i`
- [ ] Run `npm start`
- [ ] Get added to the Git repo so you can contribute!

---

This is a 👀 Tracking Issue
